[package]
name = "syn"
version = "0.6.0" # don't forget to update version in readme
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Nom parser for Rust items"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/syn/"
include = ["Cargo.toml", "src/**/*.rs"]

[features]
default = ["parsing", "printing"]
aster = []
fold = []
full = []
parsing = []
printing = ["quote"]
visit = []

[dependencies]
clippy = { version = "0.*", optional = true }
quote = { version = "0.1.2", optional = true }
